### ISSUE TITLE
Rename command completed to command executed

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician-logger#1]
Just a minority to be consistent with CommandExecuted event.

**Comment by rosstuck** [comment]
Gonna sleep on this one. I actually forgot about the Event being named that and considered a couple variations here and went with Completed since it doesn't confused anyone with being the first action in the sequence nor in the case of a queue do we know if was actually executed, just that our part in it finished (I'm aware that Completed could be construed the same way).

Will ponder tonight and probably tweak tomorrow. :)

**Comment by rosstuck** [comment]
If we wanted to be completely consistent everywhere, maybe we should rename both to CommandHandled, since the method is now called `handle()`? Neither package has a ton of downloads yet so it shouldn't be a hugely disruptive change.

**Comment by sagikazarmark** [comment]
Agreed.

**Comment by rosstuck** [comment]
All good here and first logger release tagged! Hope this helps. :)

**Comment by sagikazarmark** [comment]
:+1:
