### ISSUE TITLE
log Context did not used

### ISSUE THREAD

**Issue by tyx** [thephpleague/tactician-logger#4]
Hey guys.

Is there any good reason do add properties values directly into the message instead of adding them into the log context ? Would be more clean as the serialization would be the monolog responsability. And more reliable to use some stuff like the GelfHandler of monolog

I'm available to make the PR if you are ok.

**Comment by rosstuck** [comment]
Hi @tyx, thanks for opening this issue!

That sounds pretty reasonable to me. The only part I'm not sure about is how to format all the "extra" parameters into the log message since we don't always know what those will be (depends on the command) but if you've got an idea for it, that sounds pretty cool.

Go for it :+1:
